# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import draceditor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.ImageField(upload_to='')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Images',
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('summary', models.CharField(blank=True, max_length=255, null=True, verbose_name='Общее')),
                ('body', draceditor.models.DraceditorField(verbose_name='История')),
                ('created_at', models.DateTimeField(verbose_name='Создано в')),
                ('published_at', models.DateTimeField(verbose_name='Опубликовано в')),
                ('uuid', models.UUIDField(blank=True, null=True, unique=True, verbose_name='UUID')),
                ('url_slug', models.CharField(max_length=150, unique=True, verbose_name='URL')),
                ('lang', models.PositiveSmallIntegerField(choices=[(1, 'Rus'), (2, 'Eng')], default=1, verbose_name='Язык')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано?')),
                ('is_page', models.BooleanField(default=False, verbose_name='Отдельная страница?')),
                ('head_image', models.ForeignKey(blank=True, db_column='head_image_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Image', verbose_name='Картинка к посту')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'db_table': 'posts',
                'ordering': ('-published_at',),
            },
        ),
    ]
