# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 11:21
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=markdownx.models.MarkdownxField(verbose_name='Body'),
        ),
    ]
