# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_squashed_0005_auto_20170903_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='webp',
            new_name='thumb',
        ),
    ]
