# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 13:02
from __future__ import unicode_literals

from django.db import migrations
import draceditor.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170902_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=draceditor.models.DraceditorField(verbose_name='Body'),
        ),
    ]
