# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170903_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feed',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Основной'), (2, 'Лайв')], default=1, verbose_name='Лента'),
        ),
    ]
