# Generated by Django 2.0 on 2017-12-14 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='head_image',
            field=models.ForeignKey(blank=True, db_column='head_image_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.PostImage', verbose_name='Картинка к посту'),
        ),
    ]
