# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import draceditor.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170902_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='Общее'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=draceditor.models.DraceditorField(verbose_name='История'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано в'),
        ),
        migrations.AlterField(
            model_name='post',
            name='head_image',
            field=models.ForeignKey(blank=True, db_column='head_image_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Image', verbose_name='Картинка к посту'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_page',
            field=models.BooleanField(default=False, verbose_name='Отдельная страница?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='lang',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Rus'), (2, 'Eng')], default=1, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано в'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='post',
            name='url_slug',
            field=models.CharField(max_length=150, verbose_name='URL'),
        ),
    ]
