# Generated by Django 2.0 on 2017-12-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171214_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments_disabled',
            field=models.BooleanField(default=False, verbose_name='Отключить комменты'),
        ),
    ]
