# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170903_1808'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='PostImage',
        ),
        migrations.AlterModelOptions(
            name='postimage',
            options={'verbose_name': 'Картинка к посту', 'verbose_name_plural': 'Картинки к постам'},
        ),
    ]
