# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170902_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Общее'),
        ),
    ]
